# This is a basic workflow to help you get started with Actions

name: deploy_ubuntu_1804

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
          enable-AzPSSession: true
          # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
          # Set this value to true to enable support for accessing tenants without subscriptions
          allow-no-subscriptions: false

      - name: Packer GitHub Actions
        env:
          client_id: ${{ secrets.client_id }}    
          client_secret: ${{ secrets.client_secret }}    
          tenant_id: ${{ secrets.tenant_id }}    
          subscription_id: ${{ secrets.subscription_id }}
        # You may pin to the exact commit or the version.
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          # command to execute
          command: build
          # arguments for command
          arguments: -on-error=cleanup -var location=australiaeast -var resource_group=ol-rg-mgmt-services-p-syd-19 -var gallery_name=olsigsyd19 -var image_name=Ubuntu2004_20210914 -var image_version=2021.09.14 -var client_id=$client_id -var client_secret=$client_secret -var tenant_id=$tenant_id -var subscription_id=$subscription_id
          # file(s) to target
          target: ${{ github.workspace }}/images/linux/ubuntu1804.json
