# This is a basic workflow to help you get started with Actions

name: deploy_ubuntu_1804

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=dateformatted::$(date +'%Y.%m.%d')"
      - name: set json
        id: set
        run: |
          echo ::set-output name=json_var::'${{ secrets.AZURE_CREDENTIALS }}' 
      - name: Packer GitHub Actions
        uses: hashicorp/packer-github-actions@master
        env:
          clientId: ${{ echo $json_var | jq '.clientId') }}
        with:
          # command to execute
          command: build
          # arguments for command
          arguments: -on-error=cleanup -var location=australiaeast -var resource_group=ol-rg-mgmt-services-p-syd-19 -var gallery_name=olsigsyd19 -var image_name=AzDevOpsAgentUbuntu1804 -var image_version=${{ steps.date.outputs.dateformatted }} -var client_id=${{ env.clientId }} -var client_secret=${{ secrets.client_secret }} -var tenant_id=${{ secrets.tenant_id }} -var subscription_id=${{ secrets.subscription_id }}
          # file(s) to target
          target: ${{ github.workspace }}/images/linux/ubuntu1804.json
